# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='purchased_items',
            field=models.ManyToManyField(related_name='purchased_item_users', through='items.UserPurchasedItem', to='items.Item'),
        ),
        migrations.AddField(
            model_name='user',
            name='shopping_list_items',
            field=models.ManyToManyField(related_name='shopping_list_item_users', through='items.UserShoppingListItem', to='items.Item'),
        ),
    ]
